
GET http://192.168.1.38:3000/tasks 
###

POST http://192.168.1.38:3000/tasks HTTP/1.1 

 

{

       "title":"title 5",
       "subTitle":"subTitle 5",

} 
###
DELETE http://192.168.1.38:3000/tasks/6 HTTP/1.1 

### 
PATCH http://192.168.112.1:3000/tasks/1 HTTP/1.1 

